### ISSUE TITLE
Fail on python manage.py createsuperuser

### ISSUE THREAD

**Issue by unixfox** [TheMetaphorer/OCN-XMLChecker#5]
I tried to run `python manage.py createsuperuser` but the command failed with this error :

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 50, in execute
    return super(Command, self).execute(*args, **options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 81, in handle
    default_username = get_default_username()
  File "/usr/lib/python2.7/site-packages/django/contrib/auth/management/__init__.py", line 177, in get_default_username
    auth_app.User._default_manager.get(username=default_username)
  File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "auth_user" does not exist
LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "auth_user...
```

**Comment by doriand01** [comment]
I've got it working just fine.

```
(env)xxxx@xxxx:/opt/env/OCN-XMLChecker$ python manage.py createsuperuser
Username (leave blank to use 'mayatta65'): test
Email address: test@test.com
Password: 
Password (again): 
Superuser created successfully.
(env)xxxx@xxxx:/opt/env/OCN-XMLChecker$ 
```

Are you sure you're not having a problem with your postgres database? Have you tried running "python manage.py makemigrations" after installing the site?

**Comment by doriand01** [comment]
Have you tried migrating the models before you tried creating your superuser? If you don't migrate first then it won't work.

**Comment by unixfox** [comment]
I'll tried, sorry for no reply since a couple a days.

**Comment by doriand01** [comment]
I'm closing this issue, I don't believe this is a server-side bug, I think you forgot to migrate the models. Before you can create a superuser you must run `python manage.py makemigrations` and `python manage.py migrate`
